### PR TITLE
Add queuing functionality similar to Spotify's "Up Next" functionality

### PR DESCRIPTION
**Pull request by valevalorin**
- Relevant issue: https://github.com/Soundnode/soundnode-app/issues/530
- Created a directive to power an additional button that was placed in the views/common/tracks.html template that queues the song to be played sometime after the current.
- Modified how the queue decides what queue list item to add the 'active' class to
  - previously used songId, now matches the queueService's current position to the index of the queue list item
- Explanation of queuing implementation
  -  When a track is queued and a subqueue does NOT currently exist
      - a subqueue is created by noting the current track position in the queue and the subqueue length counter is set to zero
      - the track to be queued is inserted into the queue after the currently playing track
      - the subqueue length counter is incremented by one
  - When a track is queued and a subqueue does currently exist
    - the track to be queued is inserted into the queue at a position equal to the index of the start of the subqueue plus the current length of the subqueue (ie the end)
    - the subqueue length counter is incremented by one
  - Subqueue reset
    - a currently active subqueue will be reset under the following conditions:
      - the queue's current position moves OUTSIDE of the current subqueue (currentPosition < subqueueStart || currentPosition >= subqueueStart + subqueueLength), via using the previous or next buttons, or the player playing through the entire subqueue
      - a song is clicked, triggering immediate playback
    - after a subqueue reset, when another track is queued up it will be create a new subqueue as described above
  - NOTE: I understand I took liberties in deciding exactly how this behaves, if you want it to behave differently let me know

### CODE REVIEW

**Comment by weblancaster** [comment]
@valevalorin thanks for the PR.

I'm finishing up last details on #894 and then I'm going to take a look here.

**Comment by valevalorin** [comment]
Awesome. I appreciate the update!

**Comment by weblancaster** [comment]
@valevalorin what are we trying to accomplish here? not the technical decisions but what is the feat we want to implement?

**Comment by valevalorin** [comment]
It was just to add queueing functionality. I think the Soundcloud mobile app actually has this functionality now.

**Comment by weblancaster** [comment]
ok I will work on it then

**Pull request closed without merging**
