### PR TITLE
Fix scrubbing issue when UI is scaled

### LINKED ISSUE #770: Scrubbing affected by Zoom In/Out
Scrubbing Changes/is Inaccurate when Zoomed In/Out 

Version: Release 0.6.4 for Mac
Downloaded from: soundnodeapp.com
OS: OSX El Capitan 10.11.5

How to reproduce:
 - Open Soundnode App
 - Play any song
 - Zoom in or out using ⌘ + or ⌘ - 
- Try to scrub to any location in the song 
Actual result:
 - the song play cursor doesn't move to the location where the mouseclick happened - the zoom shouldn't actually affect this part of the GUI

### PR DESCRIPTION
**Pull request by jakejarrett**
Incorporate scaling into the seek logic so it should be the correct percentage of where you clicked :smile_cat: 

Closes #770

### CODE REVIEW

**Comment by weblancaster** [comment]
great @jakejarrett I'm going to test tonight

**Comment by jakejarrett** [comment]
@weblancaster any updates on this?

**Comment by weblancaster** [comment]
checking now.

**Comment by weblancaster** [comment]
@jakejarrett this fix changed how it works.

I can't click on any point and jump anymore.. just dragging

**Comment by jakejarrett** [comment]
@weblancaster That doesn't appear to be the case for me (Scale set both to positive / negative values and default scale setting)

**Pull request merged**
