### PR TITLE
Fix track like button hover state

### PR DESCRIPTION
**Pull request by Pitros**
Fix for [that](https://dl.dropboxusercontent.com/u/25785523/ShareX/2016/02/2016-02-05_17-27-14.mp4) nice behavior.

### CODE REVIEW

**Comment by weblancaster** [comment]
We shouldn't show play when hovering like.

**Comment by Pitros** [comment]
@weblancaster but my PR fixes that bug...

**Comment by weblancaster** [comment]
Can you describe the bug please @Pitros

**Comment by Pitros** [comment]
Currently when you hover on like button while being on track page, play icon shows up on track atwork because one variable is used in both places. Just like on the video i've attached.

**Comment by weblancaster** [comment]
Oh ok now I got it.. I thought you were actually adding this feature. can you fix the conflicts and I will merge. thanks @Pitros

**Comment by Pitros** [comment]
@weblancaster fixed.

**Comment by grant-h** [comment]
The mp4 link is dead due to dropbox rate limiting. Could you rehost somewhere else for the record?

**Comment by Pitros** [comment]
Please launch the app, go to track page for any tack you want and hover on like button to see that atwork hover state is also triggered.

**Pull request merged**
