### PR TITLE
Linux Support

### LINKED ISSUE #69: Linux Support
Seems like everything is ok for running this on ubuntu-based linux distros *(tested on Linux Mint 16 - MATE desktop)*.

**It would be great if more people could test this**. I've been so happy by seing spotify supporting linux :P An opensource soundcloud client implementation supporting it as well would be awesome! 

For making it happen i just had to enable the build for linux64 at the `Gruntfile.js`, ran `grunt build` (which then generates a pure  `Soundnode-App.nw` at `/dist/releases/Soundnode-App`) and then openned it with `nw` for linux.

There's also something to be noticed: when building with `linux64` enabled an error is raised (*Fatal error: incorrect header check*) but that does not prevent the build.

### PR DESCRIPTION
**Pull request by jakejarrett**
This brings linux support to Soundnode, Have tested it on Ubuntu 15.04 64 Bit (Gnome DE)

Everything works as expected.

Fixes #69

Related to Soundnode/soundnode-app-site#9

### CODE REVIEW

**Comment by Pitros** [comment]
Add note about Linux support in readme as well. Anyway nice work.

**Comment by weblancaster** [comment]
I haven't been able to look into this yet.. but I'm downloading and planing to install Ubuntu on my VM tonight and test this PR.

Thanks @jakejarrett

**Comment by jakejarrett** [comment]
I've added the README amendment. Not sure if it works on 32bit yet.

**Comment by weblancaster** [comment]
Hey @jakejarrett can you add the audio lib to the PR please.

**Comment by jakejarrett** [comment]
@weblancaster Added libffmpeg to /assets/

**Comment by weblancaster** [comment]
Great! thanks @jakejarrett

**Comment by weblancaster** [comment]
Hey @jakejarrett since I merged #304 we will need the Linux audio lib to merge this one.. a rebase with master will be necessary to get latest from master.

thanks

**Comment by jakejarrett** [comment]
@weblancaster Removed the 0.10.4 lib, The one included in #304 works for linux.

**Comment by weblancaster** [comment]
I tested on Ubuntu and worked fine.. thanks a lot @jakejarrett this is awesome!

**Comment by cirocosta** [comment]
:+1:

**Pull request merged**
