### PR TITLE
Redesign search dropdown

### PR DESCRIPTION
**Pull request by jakejarrett**
This is the basis of a more continuous design to ensure all components
are consistent throughout.

## Changes
* Move search input to the right side
* Make search input have a max width of 500px
* Use a 5px border on the left for titles of sections
* Utilize font weights more
* Make dropdown pop out from the header bar instead of the input

# Preview of design
image

### CODE REVIEW

**Comment by weblancaster** [comment]
Hey @jakejarrett can you also add an after screenshot please? thanks.

What would be great too, moving that part of the UI to React instead continuing to use Angular. Not a high requirement though.

**Comment by jakejarrett** [comment]
That part is after.

Yeah, would like to move it to react, potentially using CSS in JS with a theme provider.

**Comment by jakejarrett** [comment]
Essentially, just a HOC that provides a theme to components via the context api.

https://www.styled-components.com/docs/advanced

**Comment by weblancaster** [comment]
@jakejarrett I would keep using sass for now, I need to make some improvements in the architecture.

**Comment by jakejarrett** [comment]
Yeah that's cool, just a nice to have if can implement it in the future.

**Comment by jakejarrett** [comment]
@weblancaster is this fine to merge? I'd like to start some slight design tweaks on other things too. :+1:

**Comment by weblancaster** [comment]
@jakejarrett I thought you were going to move to React

**Comment by jakejarrett** [comment]
Yeah i originally wanted to move to react, but i think it'd probably be a bit easier to do design tweaks in place w/ angular then move to react once it's updated :smile:

**Pull request merged**
