### PR TITLE
Introduce a setting for the API Key

### PR DESCRIPTION
**Pull request by jakejarrett**
This allows users to introduce their own API key at any given point.

This isn't a perfect solution, but will give users an option at runtime to swap out the API Key if our api key is killed by the 15k play limit.

### CODE REVIEW

**Comment by jakejarrett** [comment]
Merging as this works when tested on OS X, Windows & Linux (Fresh installs)

**Comment by star114** [comment]
sounds good.

**Comment by weblancaster** [comment]
This is great @jakejarrett! thanks.

**Comment by brybalicious** [comment]
Great. Thanks! Does the API key persist if changed?

**Comment by jakejarrett** [comment]
@brybalicious should do, but need a new build with #1038 in it for it to persist key over multiple launches

**Pull request merged**
