### PR TITLE
Add additional track info

### PR DESCRIPTION
**Pull request by Pitros**
Early adaptaion of #309 
In likes view there's no repost data in API response.

### CODE REVIEW

**Comment by Chriz007** [comment]
Cool, can't wait to see how this looks!

**Comment by Pitros** [comment]
@Chriz007 almost like on yours concepts.

image

**Comment by Chriz007** [comment]
wow, that looks pretty cool! Thanks for implementing that pitros. Do you have any plans on the comments portion of it?

**Comment by Pitros** [comment]
I thought about it, and the best way imho would be separate page for track width more data like on souncloud. 
There will be engouh space for description, tags, comments and eg. download links which some artists include.
Anyway i'll probably try to do that in next days.

**Comment by Chriz007** [comment]
Okay. That idea sounds reasonably good.

**Comment by weblancaster** [comment]
Nice! thanks a lot @Pitros 

I'm going to try take a look in all your PR's this weekend.

**Comment by Chriz007** [comment]
@Pitros Have you also tried testing the info bar on other pictures? Because white on white will be hard to see. But if you make the bottom part blurry, maybe it could increase visibility.

**Comment by weblancaster** [comment]
Looks good.. thanks @Pitros

**Pull request merged**
