### PR TITLE
Show Soundnode logo in case IMG src returns 404

### PR DESCRIPTION
**Pull request by vincelwt**
It has happened to me with song "M83 - Wait (Kygo Remix) " for example.

### CODE REVIEW

**Comment by weblancaster** [comment]
hey @vincelwt we have a "solution" in place where replace the `null` image to soundnode logo.. can you check if that is working because otherwise your work might overlap with what is in place.

thanks.

**Comment by vincelwt** [comment]
I have the following :

soundnode

The console returns a 404 on this image.

So it's seems like the **null** solution isn't working for 404, at least for me.

**Comment by AHappyPandaBear** [comment]
@vincelwt Same happened to me when i start the program... After a reload, the picture was loaded..

**Comment by weblancaster** [comment]
Thanks @vincelwt

**Pull request merged**
