### PR TITLE
Packagecloud push script

### PR DESCRIPTION
**Pull request by JonasGroeger**
Currently supported:
- Debian: jessie
- Ubuntu: trusty
- Ubuntu: xenial

Add more by adding commands at the end of the file.

### CODE REVIEW

**Comment by weblancaster** [comment]
@jakejarrett what you think? can we merge this?

**Comment by JonasGroeger** [comment]
The question here is if we really want the git repository to create debian packages or not :)

**Comment by weblancaster** [comment]
If we are asking, maybe it's not a good idea then.

**Comment by weblancaster** [comment]
@JonasGroeger is this still relevant?

**Comment by JonasGroeger** [comment]
I'm working on getting this to a ppa

**Comment by JonasGroeger** [comment]
Packaging is now done at https://github.com/JonasGroeger/soundnode-app-debian/

**Pull request closed without merging**
