### PR TITLE
allow 16 volume steps instead of 10. closes #950

### LINKED ISSUE #950: Allow more granular volume controls
Currently it allows only 10 levels of volume, if possible allow more fine volume levels. Even on the lowest, its too loud for background music (without needing to adjust the master volume)

### PR DESCRIPTION
**Pull request by malindamiller**
changed the step interval to allow more volume settings

### CODE REVIEW

**Comment by weblancaster** [comment]
@malindamiller looks good but I think we are missing over here https://github.com/Soundnode/soundnode-app/blob/dfe81846176da9b55bf182a9938b05247a9a73fe/app/public/js/player/playerCtrl.js#L23

**Comment by peculiarhyp** [comment]
不懂

**Comment by jakejarrett** [comment]
@weblancaster That just defaults the volume to 100% (and then stores it local storage)

**Comment by weblancaster** [comment]
@jakejarrett @malindamiller I was going to merge but making another quick check I noticed we still missing parts.
`https://github.com/Soundnode/soundnode-app/blob/dfe81846176da9b55bf182a9938b05247a9a73fe/app/public/js/player/playerCtrl.js#L269`
and
`https://github.com/Soundnode/soundnode-app/blob/dfe81846176da9b55bf182a9938b05247a9a73fe/app/public/js/player/playerCtrl.js#L279`

**Comment by weblancaster** [comment]
no activity on this PR for a while for that reason I'm closing to keep the PRs list clean.

Feel free to contribute back with the changes required.

**Pull request closed without merging**
