### PR TITLE
Add doc to setup a valid api key

### PR DESCRIPTION
**Pull request by eliecharra**
Add simple doc to workaround for api limit  #802

### CODE REVIEW

**Comment by weblancaster** [comment]
@jakejarrett @eliecharra I will open a PR sometime this week to accommodate this and make easier for users to use the API KEY instead having to fiddle around the code.

**Comment by weblancaster** [comment]
Nice, I haven't opened the app in a while.

**Comment by felipevalois** [comment]
> In the latest version the API key can be changed from the settings panel 🙂

where???

**Comment by jakejarrett** [comment]
image

Clicking the cog icon on the top right then going to `Settings` will show this page. (Latest version being 7.0.0)

**Comment by felipevalois** [comment]
Thanks mate!

p.s. on the website the version offered for download is still 6.5


________________________________

**Comment by jakejarrett** [comment]
yeah, i don't have access to updating that repo so it remains out of date currently

**Pull request merged**
