### PR TITLE
Updating the icon, logo and placeholder images. closes #295

### LINKED ISSUE #295: [SUGGESTION] Change the Soundnode Icon to make it stand out more
Take a quick look at this screeny below. 

screen shot 2015-08-06 at 11 17 55 pm

You see the dock right? Right. Now find the soundnode app. 

...

It took you longer than you expected to find it right? 

You see where I'm going? I think changing the look of the icon would make it stand out more in a sea of icons. Now I'm not saying the current one is bad-looking. Its much better than anything I could do! But I think it could use a quick facelift so users can see them quickly. I don't expect a rapid change though. Maybe you can think about it and change it in the future.

Just my two cents! 

P.S Also, before anyone says that I can just change the icon myself, I would much rather prefer an official icon.

### PR DESCRIPTION
**Pull request by pmarquees**
Giving the application icon and the logotype some love.

The new icon
icon

And updated logo

screen shot 2016-02-02 at 16 22 28

### CODE REVIEW

**Comment by Pitros** [comment]
That's much better, but on dark background icon might not be well visible - eg. Windows 10 pinned app icons. And new placeholder for tracks/profiles would be awsome too.

**Comment by weblancaster** [comment]
He did a "square" placeholder for tracks as well @Pitros 

image

**Comment by Pitros** [comment]
Uh, i haven't seen that. That looks really great!

**Comment by weblancaster** [comment]
@pmarquees I can fix the merge conflict and push your changes but that way won't show you contribute directly to the code.. I would rather to have you displayed on the contributors as well.

Let me know if you need help with this.

**Comment by pmarquees** [comment]
I'll fix it as soon as possible!

**Pull request closed without merging**
