### PR TITLE
mpris Integration

### PR DESCRIPTION
**Pull request by jakejarrett**
This adds media key support to linux (32/64bit)

It will remove the existing dbus-node folder from mpris-service's node_modules and then replace it with a patched version that supports nw0.12.3 then builds it. This will be simplified when upstream dbus-node gets patched too.

It currently won't support all the mpris features due to #639, but for now It only provides media key support :smile_cat:

### CODE REVIEW

**Comment by jakejarrett** [comment]
@weblancaster this should work "as is", as i'd assume someone with the source code on linux should have git installed, But it can wait until the npm package gets updated with the patch if needed.

**Comment by jakejarrett** [comment]
This is ready to be tested on OS X / Windows if anyone wants to test it :+1:

**Comment by weblancaster** [comment]
Anything special I should do to test this? what should I look for @jakejarrett

**Comment by jakejarrett** [comment]
@weblancaster mainly playing/pausing/next/pause & building, it should act as if nothing has changed from the master for any OS besides linux.

**Comment by jakejarrett** [comment]
Tested a build on windows, It won't build on systems without dbus headers present (dbus.h)

Will try and solve this over the weekend @weblancaster  (preferably without adding dbus as a requirement)

**Comment by dn5** [comment]
When can we expect this PL to be on a release? Can't find it in [0.6.4](https://github.com/Soundnode/soundnode-app/releases/tag/0.6.4).

**Comment by jakejarrett** [comment]
@dn5 waiting for [node-dbus/119](https://github.com/Shouqun/node-dbus/pull/119) so cross platform support is preserved

**Comment by MarshallOfSound** [comment]
@jakejarrett If you use my fork of `mpris-service` it has the patch that you are waiting for in that PR

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/package.json#L88

**Comment by jakejarrett** [comment]
@MarshallOfSound Thanks! This appears to have fixed a fair few of the bugs i was encountering haha.

**Comment by MarshallOfSound** [comment]
@jakejarrett My patched repo also contains patched versions of the `node-dbus` package so it should just drop in to your current implementation :+1:

**Comment by jakejarrett** [comment]
Thanks @MarshallOfSound this builds perfectly on windows! :smile_cat:

**Comment by weblancaster** [comment]
I'm going to test this tomorrow.

**Comment by jakejarrett** [comment]
@weblancaster any updates?

**Comment by jakejarrett** [comment]
@weblancaster This builds & works on all supported platforms. Should be good to merge! :+1:

**Comment by jakejarrett** [comment]
Merging this, as i believe this is good to merge & it works fine on all platforms.

**Comment by dn5** [comment]
Great job guys! :+1:

**Comment by dsifford** [comment]
Can someone package this as a release? Arch linux user here -- Our package manager source builds from the releases of this repo.

Thanks 👍

**Comment by easterwood** [comment]
My media key for play/pause won't work with Soundnode. I have a MS Natural 4000 keyboard.

How do I find out whether mpris is working or not? I have version 0.6.5. from the app repository.

**Comment by weblancaster** [comment]
@easterwood the latest version on Linux has a bug and users aren't being able to play songs. Now if you are on another OS you should be able to use the media keyboard as long you don't have any other application that makes use of the media keyboard.

**Pull request merged**
