### PR TITLE
Progress bar changes

### PR DESCRIPTION
**Pull request by Pitros**
This is a work in progress pull request, there are some things to change (eg. calc track length only once, to remove remaining time, fix styles etc.). I also want to add a tooltip to hover event on progress bar with track time on that position for easier seeking through track.

Anyway tell me what you think.

### CODE REVIEW

**Comment by weblancaster** [comment]
Great.. do you know when you planning to finish or you want to work on a separate PR?

**Comment by Pitros** [comment]
Most of those changes I'll probably do in upcoming days, that tooltip may take me more time so that might be separate PR.

**Comment by weblancaster** [comment]
Ok cool, so just the progress bar `redesign` on this PR is fine.. if everything is fine I will merge and release with the rest improvements/changes/fixes

**Comment by weblancaster** [comment]
@Pitros never mind.. it's in a good state.. I'm going to merge and take from here.. thanks lot for the fast work :) I want to release a new version by this weekend.

**Pull request merged**
