### PR TITLE
Make build work without elevated provileges

### PR DESCRIPTION
**Pull request by JonasGroeger**
I think its a good idea not to require webpack and grunt to be installed globally.

### CODE REVIEW

**Comment by weblancaster** [comment]
@JonasGroeger can you fix the merge conflict and then I will be able to merge.. thanks

**Comment by JonasGroeger** [comment]
@weblancaster This should work now.

**Comment by weblancaster** [comment]
is this still needed @JonasGroeger @jakejarrett

**Comment by jakejarrett** [comment]
Would this produce the same result as using yarn? I'm not sure I follow the issue 100%

**Comment by JonasGroeger** [comment]
The problem here is that `tasks/shell.js` uses relative commands (to `$PATH`) instead of specifying the absolute one like `node_modules/.bin/…`. Only this way I can make sure that the Debian build works sucessfully.

**Comment by weblancaster** [comment]
@JonasGroeger can you take a look on this PR and check if still relevant please?

Make sure to take a look here #894 since those changes might affect your work. thanks.

**Comment by JonasGroeger** [comment]
Packaging is now done at https://github.com/JonasGroeger/soundnode-app-debian/

**Pull request closed without merging**
