### PR TITLE
[Feature] add a copy to clipboard button next to the permalink #604

### PR DESCRIPTION
**Pull request by Ajeey**
Added a feature that copies the track url to system clipboard along with a success notification toast.

### CODE REVIEW

**Comment by weblancaster** [comment]
@Ajeey the ideal way is to have an directive just like the other action buttons and not have it on AppCtrl.

**Comment by Ajeey** [comment]
@weblancaster I am creating a new .js file and when I do grunt build, fire up the app and try to find the file in the sources tab, I am unable to see the file. Seems like grunt did not include my newly created file.
How do I make sure the new file is picked up by grunt build ?

**Comment by weblancaster** [comment]
You don't need to do anything with grunt.. the only thing you need to do is, create your `copyDirective.js` and put here https://github.com/Soundnode/soundnode-app/tree/master/app/public/js/common then you put the request here https://github.com/Soundnode/soundnode-app/blob/master/app/index.html#L252

**Comment by Ajeey** [comment]
ah I see. Okay I am on it :)

**Comment by Ajeey** [comment]
@weblancaster Done ;)

**Comment by weblancaster** [comment]
Looks good @Ajeey but can you squash the commits into just one please.

You can do this
`git reset --soft HEAD~5` (5 is the number of commits you have)
then you can `git add .` and `git commit -m "your message. closes #604"` 
and and then push to the same branch you have this changes `git push origin yourbranch --force`

**Comment by Ajeey** [comment]
@weblancaster Done with the changes and thank you for the git tips learnt something new :)

**Comment by weblancaster** [comment]
Great work @Ajeey thanks a lot

**Pull request merged**
