### PR TITLE
Made search bar interactive, i.e expand with transition on focus

### PR DESCRIPTION
**Pull request by Ajeey**

### CODE REVIEW

**Comment by Pitros** [comment]
Thanks for PR. I don't see a need to add that animation while we have a plenty of free space, as well it seems bit too small while it's not focused. But it's not my choice after all.

**Comment by Ajeey** [comment]
I agree its not needed but I believe subtle animations improve the usability of the product.

**Comment by vladjerca** [comment]
I don't think it improves usability, but it does offer a nicer experience. +1

**Comment by weblancaster** [comment]
thanks for the work @Ajeey but I agree with @Pitros this is not really necessary.. works fine though.

I would suggest to try work on the real issues/bugs we have.

**Comment by Ajeey** [comment]
@weblancaster Sure thing.

**Pull request closed without merging**
