### PR TITLE
NW.js to Electron.js migration

### PR DESCRIPTION
**Pull request by weblancaster**
- [x] Electron prebuilt (cb92aaa67aa7a8ece2380f74f53293d178bbbef0)
- [x] Replace NW.js references to Electron references (7e7455102d4c0d4cf679f16a04d311357eda6294 48513be411b4457e5dd5de4e8ab670fee3d7ab20)
- [x] Soundcloud authentication (48513be411b4457e5dd5de4e8ab670fee3d7ab20, d716ee068627068aa5eac830f8752210d3bc7e5e. bc7371297b8b377f8f0576f84e9a0dd6a04b0e6b)
- [X] Window helpers (quit, minimize, hide, maximize) (48513be411b4457e5dd5de4e8ab670fee3d7ab20)
- [X] Package distribution (Win, Mac, Linux) (a45f3b35ce92ee4018526c5f5c3d1bfd53b6009a 72d9c6f701bf5d7c03551258685218e4e5c8c7d9)
- [X] Native media keyboard (play/pause, previous/next) (3a411e681ae7091afa0d27fff87016e08a2df504)
- [X] Window notifications (9d19829044870f48bc1db38512377c3b3ba55a6f)
- [x] Scale and Devtools shortcut
- [x] Build App menubar (54e1807499b2cf4a8637aef0fc02b2fb44cad26f)
- [ ] test, test, test (5fed52801c62aae5da176390ce3cf83f1a22b3d4)

I might be forgetting something so I'm going to add as I go.

### CODE REVIEW

**Comment by wb9688** [comment]
When this is done, can we finally stop using sc-redirect.herokuapp.com?

**Comment by weblancaster** [comment]
and use what @wb9688 ?

**Comment by wb9688** [comment]
I don't know, the authentication part that's currently in Soundnode always looked like a hack to me…

**Comment by weblancaster** [comment]
It is a hack.. but there is no other way because Soundcloud expect the third party to have a domain.

**Comment by bardiharborow** [comment]
I came here to look at what's being done, but the changes are cluttered by a huge amount of style changes. Is there a particular reason these are included in this PR?

**Comment by weblancaster** [comment]
@bardiharborow I updated the `editorconfig` file so now the design of line spaces is different, if that's what you are asking though.

**Comment by weblancaster** [comment]
@wb9688 @Pitros @jakejarrett It's all migrated but would be nice if any of you could test it out.
I will be testing today and tomorrow.

Here are the files for Mac, Win and Linux https://www.dropbox.com/sh/vkyq4jbr9ol1mpg/AABHzCFPoFHes8G_Y5k2Fy9Va?dl=0 (the rate limit is being reached pretty easily this days though so you might have issues playing tracks)

To build locally you just need to run `npm run build` if you are notusing windows you will need to install wine https://www.davidbaumgold.com/tutorials/wine-mac/

that's it. thanks.

**Comment by jakejarrett** [comment]
@weblancaster MPRIS Support seems to be present out of the box, but i am unable to get audio playing (can't see devtools and it doesn't output any errors to the terminal) or use some custom shortcuts that were previously present (Scaling was the primary one)

**Comment by wb9688** [comment]
@weblancaster: I'll try it when I've time, but I can always manually set
the API keys in the localStorage to my own ones…

**Comment by weblancaster** [comment]
@jakejarrett hm yeah I removed some shortcuts and did not notice, I'm going to add back once I get a chance.

**Comment by weblancaster** [comment]
@wb9688 @Pitros @jakejarrett I have updated the build on dropbox if you are not building locally.

@jakejarrett the scale down/up works normally on mac

**Comment by SW1FT** [comment]
@weblancaster I just tried the Win build but I can't seem to be able to login. It just shows a white rectangle  popup along with another white box popup saying "This popup should automatically close in a few seconds".

**Comment by weblancaster** [comment]
@SW1FT I'm going to check here

**Comment by jakejarrett** [comment]
@weblancaster scaling works now :+1:

**Comment by weblancaster** [comment]
@jakejarrett @wb9688 @Pitros I have been fighting to get cookies on the page since when authenticating users on facebook need cookies.. for that reason I haven't update the commit.

This is the last thing I need to do but seems like the most time consuming trying solutions.

**Comment by wb9688** [comment]
@weblancaster: The build works fine, but when I press Ctrl+/, all text gets selected (like with Ctrl+A) instead of the devtools opening. Is the fullscreen mode intended or is that just some handy thing from Electron? Btw I haven't tested logging in…

**Comment by weblancaster** [comment]
I finally figured out what I needed to do to get authentication working with cookies.. This version can now be used normally.

If you have cloned the repo and have fetched this repo you can run locally and test otherwise wait until tonight (CST time) where I'm going to build a new version and put on Dropbox for anyone that want to beta test.

Thanks.

**Comment by Legitgamer264** [comment]
I would love to beta test. Thank you!

**Comment by weblancaster** [comment]
@Legitgamer264 awesome. When I get home tonight I'm going to release a beta version for us or if you have the code locally you can build `npm i && npm run package:osx`.

**Comment by Legitgamer264** [comment]
I get home from school in about 4 hours. I can get the latest updates and make it if you haven't released the beta by then. No rush on releasing the beta

**Comment by Pitros** [comment]
Great work @weblancaster, I've tested it quickly on Windows OS and:

- webpack-dev fails - https://gist.github.com/Pitros/567ab32b3962f677d24be77f9d08d735
- logging with google isn't working

And some other bugs, but probably all because of lack of bundle.js from webpack.

**Comment by weblancaster** [comment]
@Pitros yes probably because of Webpack.. going to fix it tonight.

Keep letting me know of the bugs so they can be logged here https://github.com/Soundnode/soundnode-app/projects/1

**Comment by Legitgamer264** [comment]
There is no button to close the app, no Red X or minimize button, in the electron build

**Comment by weblancaster** [comment]
Are you on Windows platform @Legitgamer264?

**Comment by Legitgamer264** [comment]
@weblancaster Yes I am

**Comment by weblancaster** [comment]
That's very likely related to the problem @Pitros mentioned where Webpack isn't transpiling the code correctly. I'm fixing it right now.

**Comment by Legitgamer264** [comment]
sounds good :)

**Comment by weblancaster** [comment]
@Legitgamer264 that should be fixed now.. trying pulling latest. Thanks for the help.

**Comment by Legitgamer264** [comment]
I am not seeing a red X or minimize button after I packaged the latest

**Comment by Legitgamer264** [comment]
@weblancaster Also, I am signed in as you, for some reason - http://i.imgur.com/AfP8Azs.png
I can't find where to log out

**Comment by jakejarrett** [comment]
@weblancaster Builds & launches fine on linux, MediaPlayPause triggers without mpris being loaded by the looks of it [Console log of it being registered](https://gist.github.com/jakejarrett/746e2079e433c8acaaf529e76c234be2#file-soundnode-error-log-L15)

**Comment by weblancaster** [comment]
The bigger issue now is the authentication with Google.. going to try to figure out the next days otherwise I'm just going to remove the button.

**Comment by weblancaster** [comment]
@Legitgamer264 Ha that's because I have forgot to remove the userConfig.. try `git pull origin electron-migration` that should remove the userConfig from the repo

**Comment by Legitgamer264** [comment]
@weblancaster I will do that when I get home from school. Thank you

**Comment by JonasGroeger** [comment]
Please notify me when the project is done since I will probably have to update the build script for continuous deployment.

**Comment by weblancaster** [comment]
@jakejarrett does it mean we can remove the mprisService  and the condition in playerCtrl code?

**Comment by Legitgamer264** [comment]
@weblancaster I am not seeing a red x or minimize button in the app. I just pulled to make sure I have the most recent one

**Comment by weblancaster** [comment]
Hm ok then I'm going to take a look tomorrow.. thanks for letting me know @Legitgamer264

**Comment by Legitgamer264** [comment]
Thank you

**Comment by jakejarrett** [comment]
@weblancaster Yeah, either way it should be removed in the port. I should have fully removed it originally.

**Comment by Legitgamer264** [comment]
@weblancaster would there be a way to make it so that "Ctrl+/" work so that I can run the python script to get an access token regarding the API limit issue? I can't seem to get that command to work on the electron version

**Comment by weblancaster** [comment]
@Legitgamer264 you should be able to see the developer tools option on the top menu.

The shortcut should be the same your chrome browser `ctrl (or command if on mac) + alt + i`

screen shot 2016-12-15 at 11 30 36 am

**Comment by Legitgamer264** [comment]
@weblancaster I can check when I get home but yesterday I didn't have a menu. No settings button or anything. I'm on windows

**Comment by weblancaster** [comment]
Hm ok so try the shortcut that should work.

**Comment by Legitgamer264** [comment]
I will try that when I get home

**Comment by Legitgamer264** [comment]
I got the Developer tools to open. Any update on getting the settings, Red X and minimize buttons into the electron build?

**Comment by Legitgamer264** [comment]
@weblancaster Something I noticed. In the electron build, I can't play a song and I get this http://i.imgur.com/vDGd1k6.png in the Console. But when I use the non electron build, from Master Branch, I can play songs and music just fine.

**Comment by jakejarrett** [comment]
@Legitgamer264 Can you run `npm run webpack:dev` to build the bundle?

**Comment by wb9688** [comment]
@Legitgamer264: And have you restarted Soundnode after you've put in the
Client ID and Access Token from my Python script into the `localStorage`?

**Comment by weblancaster** [comment]
@Legitgamer264 you can't play because we had have reached the API limit (that's what the 429 error is), now the numfmt is something not too concerning but I have on my list to get fixed.

**Comment by Legitgamer264** [comment]
@wb9688 yes I have. I did it a few times and it didn't work

**Comment by Legitgamer264** [comment]
@weblancaster sounds good. I had a feeling it was related to the API limit being reached

**Comment by wb9688** [comment]
@Legitgamer264: Does the console show the Client ID from my Python script?
If not, the auth code of this Electron version has changed and I'll take a
look tomorrow. Else, does it work when running my Python script again?

**Comment by Legitgamer264** [comment]
@wb9688 I will let you know when I get home from school. Give me about 2hrs

**Comment by Legitgamer264** [comment]
@jakejarrett I will give That a try when I get home from school

**Comment by Legitgamer264** [comment]
@wb9688 This is what I see in my console http://i.imgur.com/oHvmdWO.png
I restarted the app and I am still getting the "cannot play track" error

**Comment by weblancaster** [comment]
@Legitgamer264 try log out and then log back in. The `ngModel:numfmt`will show up but you will be able to login.

**Comment by Legitgamer264** [comment]
@weblancaster I am able to get the Minimize, X, and settings, etc buttons to appear. But I still can't play any track. Is this still because of the API? It's been a few days since I was able to play a track

**Comment by wb9688** [comment]
@Legitgamer264: Soundnode doesn't use the `localStorage` for getting the Client ID and Access Token, instead it uses the following code:

```js
const fs = require('fs');
const userConfig = JSON.parse(fs.readFileSync(`${__dirname}/userConfig.json`, 'utf-8'));

// set window access token
window.scAccessToken = userConfig.accessToken;

// set window clientId
window.scClientId = userConfig.clientId
```

Which means there's a `userConfig.json` file that stores the Client ID and Access Token…

**Comment by weblancaster** [comment]
@Legitgamer264 yes usually by 3pm CST Soundnode reached the API limit already so then just in the next day.

Weekends not as much people use so you will be able to use for longer (mostly during the mornings and beginning of the afternoon).

**Comment by wb9688** [comment]
@weblancaster: Can you make `npm run clean` able to run on Windows? Windows doesn't have the `rm` command, so you should use something like [`rimraf`](https://www.npmjs.com/package/rimraf)…

**Comment by weblancaster** [comment]
@wb9688 good point.. going to do that today. thanks.

**Comment by Legitgamer264** [comment]
@wb9688 do you have any idea when your python script will be fixed to work with the electron build?

**Comment by weblancaster** [comment]
@Legitgamer264 try changing the `clientId` here with yours https://github.com/Soundnode/soundnode-app/blob/electron-migration/main.js#L14

**Comment by Legitgamer264** [comment]
@weblancaster I got it to work. But you have to also change app/public/js/system/userConfig.json, and put in the AccessToken and ClientId in that file too. That along with changing the clientID in main.js will work

**Comment by weblancaster** [comment]
@Legitgamer264 I'm adding the `accessToken` and `clientId` to `userConfig.json`.

You can take a look here https://github.com/Soundnode/soundnode-app/blob/electron-migration/main.js#L73

**Comment by Legitgamer264** [comment]
@weblancaster so from now on all I have to do is adjust the main.js?

**Comment by weblancaster** [comment]
I have pushed new commits so if anyone wants to test please pull latest. thanks.

**Comment by Legitgamer264** [comment]
I will pull the latest when I get home

**Comment by Legitgamer264** [comment]
@weblancaster When I logged out and went to sign back in, I get this window - http://i.imgur.com/REx9wWy.png
I checked and the userConfig.json is not in app/public/js/system
but I looked into the main.js and if I have the general idea of the code, if the userConfig doesn't exist isn't it supposed to open up the authentication window?

**Comment by Legitgamer264** [comment]
@wb9688 so what would the script be to get the clientID and accessToken for the electron build? since that is the one I am using at this time

**Comment by wb9688** [comment]
@Legitgamer264: The Python script is always the same, because it just gets
some tokens from SoundCloud, but the place where you need to paste the
tokens is different in this Electron build, I haven't yet had the time to
look at the Electron build, so you should ask @weblancaster, btw tomorrow
I'll _probably_ make a patch for the Electron build à la my patch for the
"old" Soundnode…

**Comment by Legitgamer264** [comment]
@wb9688 thank you. I have ran the script and copied the access token and clientID into the userConfig, and I changed the clientID in the main.js file too but whenever I package the app up and then run the exe, I still get the API limit error. idk what I am doing wrong

**Comment by wb9688** [comment]
@Legitgamer264: The errors show a Client ID in the URLs, is that one the same as the one you just copied from my Python script?

**Comment by Legitgamer264** [comment]
@wb9688 I am using the same clientID that I get from your script. Same with the access token. I put the accessToken and ClientID in the userConfig located in (for me) soundnode-app\dist\Soundnode\Soundnode-win32-x64\resources\app\app\public\js\system

**Comment by Legitgamer264** [comment]
@weblancaster I think I found the issue on why the clientID and accesstokens that I get from the python script aren't working. I tried the build on my laptop, before the update on 12/19, and I was able to play songs just fine. But when I pulled the latest electron from today, that is when I got the API limit error. I am not sure which of the changes that were made that caused it to not work. But I know its the latest update from today that is causing it. I am pretty sure of that

**Comment by kokarn** [comment]
Pretty sure it's just the keys that are limited because of the number of
plays. Nothing to do with Electron or NW

**Comment by weblancaster** [comment]
Merging this work in master since soon or later that will happen and we are not changing anything in master.

**Comment by Julien81** [comment]
Hi, I'm trying to run the app from the git repository, I'm on MX16...
The ctrl+/ doesn't work on electron and since I'm on linux I don't have the shortcut "toggle developpement kit" so as long as it give me the "can't play" error I can't try the Python code of wb9688.
Btw I'm on 32bit archi so I can't try the prebuilt linux version. Any help would be nice, thanks for the work done here.

**Comment by Julien81** [comment]
Hi, well connected on my soundcloud account using either the login and password on the app or using the user id and token from the python code from wb9688.
In both ways I still can't play any music with the same error as I've read everywhere "something went wrong [...]" so maybe as Legitgamer264 say, there is a problem with the version of electron.
I'm newbie here so I'm not sure of successing downgrading electron properly for the moment. Thanks for the job done here!

**Comment by weblancaster** [comment]
All the master has latest fixes which I'm going to release a test version tonight for anyone who is interested. Or just build from master if you don't want/need to wait for me to release.

**Pull request merged**
