### PR TITLE
Update package.json

### LINKED ISSUE #1077: [all os's] Icons are pointing to the wrong files
Icons aren't where they should be, which is the cause of surprising results.

Version: All
Downloaded from: built from github clone
OS: All

How to reproduce:
 - Clone the repo `git clone git@github.com:Soundnode/soundnode-app`
 - Build the app `cd soundnode-app && yarn && yarn package:all`
Actual result:
 - See the icons not working correctly

### PR DESCRIPTION
**Pull request by etaletai13**
Small update to icon filenames in package.json

This will fix #1077

### CODE REVIEW

**Comment by etaletai13** [comment]
? any reviewers here?

**Comment by jakejarrett** [comment]
Sorry just got to reviewing this now, the icons still don't work on linux (Namely on Gnome shell w/ ubuntu dock extension running)

**Comment by etaletai13** [comment]
@jakejarrett Okay, thanks!

**Comment by jakejarrett** [comment]
@etaletai13 Any update on this in re to linux icons not working?

**Comment by jakejarrett** [comment]
Will close as it's a year old, If you want to proceed with updates just re-open & push the updates.

**Pull request closed without merging**
