### PR TITLE
Refresh stream

### PR DESCRIPTION
**Pull request by cdtinney**
[FEATURE] Auto-refresh Stream #297

Add manual refresh button (icon) for stream page

### CODE REVIEW

**Comment by weblancaster** [comment]
@cdtinney can you put an screenshot attached here please.

**Comment by cdtinney** [comment]
refresh-stream

**Comment by Pitros** [comment]
Wouldn't using just '$route.reload();' be simpler? 
As well your stream.html still has filter directive which has been removed a while ago.

**Comment by cdtinney** [comment]
@Pitros removed the directive.

Just tried using $route but I receive errors when I try to include it. I did some Googling and found that angular-ui-router has a $state.reload() function but that doesn't seem to be reloading the controller either.

**Comment by weblancaster** [comment]
Try using 

```javascript
$state.transitionTo($state.current, $stateParams, {
                        reload: true,
                        inherit: false,
                        notify: true
                    });
```

**Comment by Pitros** [comment]
First of all, can you clone lastest version of repo? Because once again you're adding code that has been removed. Second, I think that refresh button is too big.

**Comment by jakejarrett** [comment]
I think it would make more sense for it to be in the navigation, as it wouldn't be useful to scroll to the top just to reload the page (I assume reloading will reset scroll position)

**Comment by SaahilMehta** [comment]
Is this feature still in progress?

**Comment by cdtinney** [comment]
@SaahilMehta Sorry - had pushed this aside. I can make the changes @Pitros and @jakejarrett mentioned this week.

**Pull request closed without merging**
