### PR TITLE
[FEATURE] - Reworked Top 50 Charts to be able to filter by genre

### PR DESCRIPTION
**Pull request by fishr01**
The updated will bring an option to listen to the top 50 for each genre - much like on the current soundcloud website.

### CODE REVIEW

**Comment by cenderin** [comment]
Nice!, can't wait for the next release with this in it.  Good work!

**Comment by weblancaster** [comment]
@fishr01 this is a great work.. would you fix the conflicts before I can merge please?

**Comment by fishr01** [comment]
@weblancaster Great! Glad you like it, actually my first time working on these technologies. Will fix it up quick and update.

**Comment by fishr01** [comment]
@weblancaster Okay that felt like alot more work that it should of been. Let me know if I need to correct any of this.

**Comment by weblancaster** [comment]
Great job @fishr01 people are going to love this.. I'm just going to do some minor ui updates.

**Comment by fishr01** [comment]
@weblancaster Awesome! This is my first decent contribution to a public repo! Feelsgood!

**Comment by Pitros** [comment]
@weblancaster are you going to work on those button list aswell? (If not I would like to try to replace them with more ux friendly option)

**Comment by weblancaster** [comment]
Yes I did some improvements already checkout #595

**Pull request merged**
