### PR TITLE
Add OS X application menu

### PR DESCRIPTION
**Pull request by jakehh**
The main benefits of adding an OS X Application Menu is getting native shortcuts (CMD+Q To Quit the application, CMD+H To Hide The application etc)

### CODE REVIEW

**Comment by weblancaster** [comment]
This is great @jakehh 

Can you add this to `core.js` part of the object `appSystem` please?
https://github.com/Soundnode/soundnode-app/blob/master/app/public/js/system/core.js#L8

then I will merge.

Thanks

**Comment by jakehh** [comment]
I can change the code a bit so theres a different menu for when the user is logging in & when the user is logged in?

**Comment by weblancaster** [comment]
Hey @jakehh I really appreciate your suggestions and contribution.

Now asking your questions I would say to always ask the question `Is this going to improve the user experience or make the App faster or improve the Software Design?` if so send as a feature/improvement branch each work separately please.

About the improvement/bug on the audio scrubber.. please open a issue just to for that issue.

And thanks for your sidenote I will think about it with those questions I said in mind.

**Comment by jakehh** [comment]
I should have thought it through a bit more haha, The basis is the user shouldn't be able to access the play function if it isn't ready yet.

But the only things i'm unable to implement are Shuffle/Repeat & new Playlist (Playlists should be really easy to implement, but i get a TypeError)

**Comment by weblancaster** [comment]
@jakehh this is great! Thanks.

I will do a small refactoring though.

**Pull request merged**
