### PR TITLE
add selectable text. closes #443

### LINKED ISSUE #443: [Feature] Highlight & copy text, any text
I think it'd be useful to have the ability to highlight text anywhere within the SoundNode window to copy to the Windows clipboard.  I often find myself copying tracks from tracklists for later and find it frustrating to have to open the permalink to a mix, copy, close the tab, and go back to SoundNode.  Is it possible to make this a simple add within the SoundNode app window?

### PR DESCRIPTION
**Pull request by weblancaster**

### CODE REVIEW

**Comment by Chriz007** [comment]
yay, you're back! :)

**Comment by weblancaster** [comment]
Haha @Chriz007 I have been working on a new app/project and it's taking most of my time since I'm building full stack from scratch.

But I always keep an eye on here.

**Comment by Skkiz** [comment]
Sweet! What is it called?


On January 7, 2016 at 7:34:14 PM, Michael Lancaster (notifications@github.com) wrote:

Haha @Chriz007 I have been working on a new app/project and it's taking most of my time since I'm building full stack from scratch.

But I always keep an eye on here.

**Comment by weblancaster** [comment]
`Solshal` is the name of my new son.

**Pull request merged**
