### PR TITLE
Made it compatible with npm3, fixes #524

### LINKED ISSUE #524: Stuck at "Authentificating your Soundcloud account" when developing locally

### PR DESCRIPTION
**Pull request by wb9688**
I made it compatible with npm3 by adding all dependencies of `universal-analytics` to the nwjs Grunt task, which fixes #524...

### CODE REVIEW

**Comment by weblancaster** [comment]
Hm this will be a problem once we need to add more node modules, won't scale easily.

Let me think what we can do about it then I get back to you.

**Comment by wb9688** [comment]
Indeed it won't scale easily, but afaik there's no other way to do it...
Op 1 feb. 2016 21:15 schreef "Michael Lancaster" <notifications@github.com>:

**Comment by jakejarrett** [comment]
Would it not be simpler to do something like
```
'./node_modules/**/**/', !'./node_modules/whatever_shouldnt_be_included'
```

**Comment by wb9688** [comment]
@jakejarett Nope, because that whould be around 7 times longer... Does
someone (@weblancaster, @pitros or @jakejarret) have a better idea?
Op 3 feb. 2016 08:58 schreef "Jake Jarrett" <notifications@github.com>:

**Comment by Pitros** [comment]
Let's just replace `universal-analytics` module with different one? It might be event that simple angular plugin: https://github.com/panrafal/angular-ga and should do the job - it only needs to send current pagename.

**Comment by wb9688** [comment]
@pitros that's a possibility, but then we have to rewrite the ga related
code, I'll **try** to do that tomorrow...
Op 4 feb. 2016 22:11 schreef "Piotr Cholewa" <notifications@github.com>:

**Comment by Pitros** [comment]
@wb9688 that's 10-15 lines of code, IMHO still better way to do that.

**Comment by wb9688** [comment]
@Pitros Or something like this:

```js
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
```

**Comment by wb9688** [comment]
Closed as of #625...

**Pull request closed without merging**
