### PR TITLE
Quick fixes for errors in JS execution + artist names on follower pages

### PR DESCRIPTION
**Pull request by dgattey**
Found a few small JS bugs related to data returned from the API that I fixed, plus an inconsistency in HTML I fixed.

1) Searching may return less than 4 items, but the length of the collection was hardcoded, making the search results inaccessible if the search returned less than 4 items (search for "calvin har" in the current version to see this).
2) If the user didn't have a description, followers wouldn't show up either because we assumed `data.description` would exist. Simple null check.
3) Followers/following pages didn't have a link to the user if you clicked on the name of the user rather than the photo (despite the pointer cursor). So I added a link.

### CODE REVIEW

**Comment by dgattey** [comment]
Anything to fix here? If not, what can I do to help merge it in?

**Comment by jakejarrett** [comment]
I'll test this tonight

**Comment by jakejarrett** [comment]
@dgattey Tested it finally (sorry for the delay) Everything looks good to me.

**Comment by weblancaster** [comment]
Based on @jakejarrett I'm accepting this PR.. thanks @dgattey and thanks @jakejarrett for testing.

**Pull request merged**
