### PR TITLE
Feature: Makefile and debian packaging for linux64

### PR DESCRIPTION
**Pull request by JonasGroeger**
Hello!

I added a Makefile and a way to create a debian package out of this software. To create the debian package, run `debuild` in the project root. This will create a `*.deb`, like `soundnodeapp_0.6.1-1_amd64.deb` in the parent directory `..`.

To sign the build with your custom key, not the maintainers one (mine), you need to pass the parameter `-k` to debuild, like this:

    debuild -k<YOUR_KEY_ID>

For example

    debuild -k330D89B5

*Pull request to 'master', since 'dev' didn't exist*

### CODE REVIEW

**Comment by jakejarrett** [comment]
@JonasGroeger this is awesome, I will test it on Ubuntu tonight :smile_cat:

**Comment by weblancaster** [comment]
@jakejarrett you are the man.. haha thanks for testing this I will trust your judgment on this and merge once you give green light

**Comment by jakejarrett** [comment]
It fails on the last step due to a missing secret key, I'm not sure if this is an error on my part (I'll be able to test more during the weekend)

```
Finished running lintian.
Now signing changes and any dsc files...
 signfile soundnodeapp_0.6.1-1.dsc 330D89B5
gpg: skipped "330D89B5": secret key not available
gpg: /tmp/debsign.sYylmpZK/soundnodeapp_0.6.1-1.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1293:
running debsign failed
```

**Comment by JonasGroeger** [comment]
@jakejarrett This is the signing part. The key `330D89B5` is mine, which you don't have the secret version of. **You need to have your GPG key in the keyring and sign it using your key id**, i.e.

    debsign -k12341234

You can create a keypair (public, private) using

    gpg --gen-key

and then following the steps. Using

    gpg --list-keys <your-mail@example.com>

you can then get your key id.

**Comment by jakejarrett** [comment]
Ah @JonasGroeger got it! Awesome, build works perfectly just need a .desktop file for the app to be show in launchers :smile_cat: but that be in a separate pr if necessary

**Comment by weblancaster** [comment]
So are we good to merge @jakejarrett ? anything we will need to add to README.md or documentation?

**Comment by jakejarrett** [comment]
This is all good, we should document the build process for building .deb package, but for now it should be fine to merge

**Comment by weblancaster** [comment]
@JonasGroeger can you document the build process for .deb package?

**Comment by weblancaster** [comment]
Thanks for testing this @jakejarrett

**Comment by weblancaster** [comment]
This is now released.

**Comment by JonasGroeger** [comment]
@weblancaster Done @ https://github.com/Soundnode/soundnode-app/wiki/Building-the-debian-package

**Comment by weblancaster** [comment]
Great thanks @JonasGroeger

**Comment by jakejarrett** [comment]
@JonasGroeger I was retesting this on ubuntu and it appears They're not building correctly on my end. Its installed to the right directory and such, but when i try to run it will just show the default nwjs page instead of Soundnode.

Lintian returns an error saying the sources are missing.

**Comment by JonasGroeger** [comment]
@jakejarrett Can you give me the output of the whole script? The lintian errors are usually normal and nothing big to worry about.

**Comment by jakejarrett** [comment]
Here's the full build log, its fairly long so i put it in a gist

https://gist.github.com/jakejarrett/e9dcd59ecc8c913a4319

**Comment by JonasGroeger** [comment]
Are you sure you posted the whole thing? I expected a signing process after lintian. Ah, I see. You didn't provide a key. Thats fine. If the run was successful, which is the case, you should have a `.deb` file in `..`.

To test the output, you can run `make install`. This will install soundnode into `/tmp/opt/soundnodeapp/`, as specified [here](https://github.com/Soundnode/soundnode-app/blob/master/Makefile#L1).

There, you can see if all nessecary files are present. The Makefile essentially does just `cp`.

**Comment by jakejarrett** [comment]
@JonasGroeger Comparing the source & installed, there's definitely a difference. The one in /opt/ is ~4MB smaller. I'll spend some time with it and see whats going on

**Pull request merged**
