### PR TITLE
Basic Settings Page

### LINKED ISSUE #382: [Feature] Settings Page
I've been working on a basic settings page where users could change settings that are built into the app.

This should allow users to make soundnode change its behavior to their liking. This uses localStorage for the settings.

screenshot from 2015-09-20 14-10-08

### PR DESCRIPTION
**Pull request by jakejarrett**
Adds a settings page to Soundnode & Ability to disable desktop notifications from soundnode.

Also adds keyboard shortcut ( control/cmd + , )

screenshot from 2015-09-20 19-47-03

Closes #382

### CODE REVIEW

**Comment by Pitros** [comment]
You could use ng-checked for settings view.

**Comment by jakejarrett** [comment]
@Pitros i'm not too familiar with ng-checked. I'll give it a try and see what i can do.

**Comment by jakejarrett** [comment]
@Pitros I switched it to ng-checked :+1: Thanks for the heads up (I misunderstood what ng-checked was for initially)

**Comment by Pitros** [comment]
Now it looks simplier :+1: , ng-model on input probably should work as well but that's a quick note.

**Comment by weblancaster** [comment]
Looks good @jakejarrett thanks for working on this.. pretty cool feature.

**Comment by weblancaster** [comment]
I just going to do some refactoring although everything works great.

**Pull request merged**
