### PR TITLE
Improvement on topBar for Macintosh. closes #501 closes #533

### LINKED ISSUE #501: OS X close/minimize/maximize buttons too big
The **close, minimize, maximize buttons are too big in OS X**, not following the [OS X Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowTitleBarToolbar.html#//apple_ref/doc/uid/20000957-CH39-SW1).

Comparative below: 

im

### LINKED ISSUE #533: Make the title bar more appealing
As the title says, I find the titlebar a bit ugly. Would do a pull request if accepted.

### PR DESCRIPTION
**Pull request by LeGfrey**
Hi guys :) 
For my first contrib I decided to improve a bit the top toolbar for macintosh (my current OS).

To answer these issues https://github.com/Soundnode/soundnode-app/issues/501 and https://github.com/Soundnode/soundnode-app/issues/533 I mainly changed the close / mini / maxmimize buttons to be smaller and more colorful. And changed a bit the Y position of elements (search bar and buttons).

Here's some screenshots of the differences.
Before : 
topbefore

After : 
topafter

### CODE REVIEW

**Comment by weblancaster** [comment]
Looks great @LeGfrey although can we make them a bit smaller? instead 10px let's try arround 7px

**Comment by christopherturner** [comment]
Yeah they should be a bit smaller to be consistent with the OS, but looks awesome, @LeGfrey  :)

**Comment by Mattijah** [comment]
There should be also a slightly darker border around the circle (button) a believe.

**Comment by iDuuck** [comment]
Smaller, but no dark border please, because it would make everything blurry. In the screenshot it is also not with a dark border.

**Comment by Mattijah** [comment]
Well, the first screenshot where is a light background there is definitely something around the circle. Good thing is that `Soundnode` has a dark bar so maybe it is not needed in this case. I don't know.

**Comment by iDuuck** [comment]
No I don't think that it is needed. Should be ok to go without a border.

**Comment by weblancaster** [comment]
What @LeGfrey did is good enough for now.. we just need to get a bit smaller from 10px to 7px maybe. no border.

**Comment by LeGfrey** [comment]
Thank you guys for you feedback :smile: 
As requested I reduced a bit the size of the buttons (around 3px).
Please tell me if it's still too large.
newtop

**Comment by iDuuck** [comment]
They need to go up a little now.. And 1-2px more close to each other

**Comment by iDuuck** [comment]
And perhaps update the screenshot on the readme

**Pull request merged**
