### PR TITLE
Added feature to resume last played track and position. Closes #484, closes #565

### LINKED ISSUE #484: [Feature] Resume last played song
In my opinion it would be cool to save the song and minute that you are playing so that when you open the app again it will resume from where you left

### LINKED ISSUE #565: Soundnode should save the played track and its position when the app is closed

### PR DESCRIPTION
**Pull request by edisonchee**

### CODE REVIEW

**Comment by Pitros** [comment]
Really nice feature, but the thing is that it doesn't work like it's supposed to for me. It does restore last played track, but it doesn't restore last position.

**Comment by edisonchee** [comment]
Bummer! That happens when the track progress isn't saved into local storage on exit. I probably need to write a more robust handler for exiting the node process. Thanks for the feedback!

**Comment by Pitros** [comment]
@edisonchee probably you should use `close` event on nw.js window (as well there might be difference in different OS behavior).

**Comment by edisonchee** [comment]
@Pitros let me know if this works. I removed the handler on process.exit and used the handler in guiConfig.js instead. I only tested it on OSX, as I don't yet have access to Linux and Windows.

**Comment by Pitros** [comment]
@edisonchee it still doesn't work, and it just can't work. Because in guiConfig.js you can't access `player.elPlayer`, so nothing will be saved. I don't know why it works for you, are you sure that you're commiting all the changes?
```
Uncaught TypeError: Cannot read property 'currentTime' of undefined
```
That's really weird, @weblancaster @jakejarrett you're both running OSX (at least you were) can you check if on OSX this somehow works?

**Comment by edisonchee** [comment]
@Pitros Sorry about that; I'm not too sure why it worked on OSX before. I ran my build on a Windows 10 machine and got the same error as you. I've since done a fix and tested on both Windows and OSX.

**Details:**
- I've opted to store and update track duration in a data attribute on the player-progress element, using the 'timeupdate' event listener in playerService.js. I believe this is much more performant than storing directly into localStorage, as the latter is a synchronous file I/O operation.
- In order to save the track duration into localStorage, I had to do it in two places; using both node process exit handler and guiConfig.close to do it.

**Comment by weblancaster** [comment]
I will try on Mac and then get back to you guys

**Comment by Pitros** [comment]
@edisonchee now it seems to be working both track with queue and track time.

**Comment by weblancaster** [comment]
@edisonchee would you fix the merge conflict please.. worked fine here.

**Comment by weblancaster** [comment]
Also.. can you merge your commits into 1?

here's how to do it.

`git log` to see your commits (from top bottom) you can see that at the moment you have 4 so to merge them.. `git reset --soft HEAD~4` then `git add .` `git commit -m "your commit message"`

**Comment by Pitros** [comment]
@weblancaster most conflicts causes `app.css.map`, shoudn't we add it to .gitignore?

**Comment by weblancaster** [comment]
I did it @Pitros I also removed app.css.map from the repo that way avoiding future conflicts..sorry for not have done this before :/

**Comment by edisonchee** [comment]
Tried to deal with the merge conflict and ended up with some weirdness. How do I resolve any merge conflicts with the main repo?

**Comment by weblancaster** [comment]
I will do it don't worry about it @edisonchee

**Comment by edisonchee** [comment]
@weblancaster thanks! Great job with the app.

**Pull request closed without merging**
