### PR TITLE
Use Fisher-Yates shuffle for shuffle functionality

### LINKED ISSUE #683: Shuffle algorithm just picks a random song to play
## Reproduction

This bug can be reproduced by clicking `.player_shuffle`.
## Expected

Shuffle randomizes the order of the items in front of `queueService.currentPosition`, leaving history as it is, and changing the future queue.
### Before
- A
- B (current position)
- C
- D
- E
- F
### After
- A
- B (current position)
- F
- E
- C
- D
## Actual

Using [`Utils.shuffle()`](https://github.com/Soundnode/soundnode-app/blob/fbe7b2169874ccced472583747d05e578b67c393/app/public/js/common/utilsService.js#L86-L91) currently just moves `queueService.currentPosition` to a random spot in the queue.
### Before
- A
- B (current position)
- C
- D
- E
- F
### After
- A
- B 
- C
- D
- E (current position)
- F

---

This may be a duplicate of #650, but there isn't enough information in that issue to work on it.

### PR DESCRIPTION
**Pull request by christianbundy**
Resolves #683 

Test case, in pure JavaScript:

``` js
var past = ['A', 'B - current', 'C', 'D', 'E', 'F']
var next = past.indexOf('B - current') + 1;
var future = past.splice(next, past.length);
    
var current = future.length, temp, random;
while (current) {
    random = Math.floor(Math.random() * current--);
    temp = future[current];
    future[current] = future[random];
    future[random] = temp;
}

console.log(past.concat(future).join('\n'));
```

**Sample output:**

>A
B - current
D
E
C
F

>A
B - current
E
C
F
D

>A
B - current
F
E
C
D

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by weblancaster** [comment]
Hey @christianbundy it's not playing random tracks anymore.. it's repeating the current track can you take a look please.

**Comment by weblancaster** [comment]
Any luck on this @christianbundy

**Comment by christianbundy** [comment]
@weblancaster Sorry, super busy -- I won't be able to add another commit today, but I believe the problem comes from the shuffle being run each time it goes to the next song. Instead, shuffle should be run when the user clicks "shuffle", and when you go to the next song there shouldn't be any shuffling.

Does that make sense? I can put together a commit in the next few days. Sorry for the delay, I've just been slammed with work this week.

**Comment by grant-h** [comment]
Question: will this be able to shuffle through my entire like's list? This is a feature that Soundcloud web really lacks. I like to hear old songs instead of the current 30 that are queued.

**Comment by dgattey** [comment]
Is this still actively being worked on? I'd love for shuffle to actually work...

**Comment by christianbundy** [comment]
If anyone wants to finish this up, it should be super easy.

[This code](https://github.com/Soundnode/soundnode-app/blob/bbd24b3dea1a75faa668cfded6f91d0dd42b2956/app/public/js/player/playerCtrl.js#L83-L85) needs to be replaced with `utilsService.shuffle();` (although I'm not sure whether `utilsService` is in scope?) and [this code](https://github.com/Soundnode/soundnode-app/blob/bbd24b3dea1a75faa668cfded6f91d0dd42b2956/app/public/js/common/playerService.js#L227) just needs to be nuked.

> Question: will this be able to shuffle through my entire like's list?

@grant-h To be completely frank, I have no idea. I've never even installed this app. My buddy mentioned that the shuffle was broken so I tried to fix it, but it looks like there's some strange stuff happening in the code above.

**Comment by dgattey** [comment]
Yeah, in my opinion, the whole queueing tracks code is a bit of a mess. Queue doesn't always seem to work well, and there are a lot of bugs on specific edge cases. I might try rewriting queuing to get a new implementation where you can add/remove songs directly, switch to a new queue when you play from a different source (Stream vs. Likes vs. playlist), etc. And fixing shuffle would be part of that. 

@weblancaster what do you think about shuffle & queue code? Is what I'm describing necessary/a feature that should be worked on right now?

**Comment by christianbundy** [comment]
I'm unable to test, but I think the code I pushed *should* work, at least better than how it was working previously. Ideally, shuffling would only happens at the tip of the queue to find another song to play, but I think this is an improvement on how it was previously working. Please let me know if there are any issues!

**Comment by cinzunzas** [comment]
IMHO,
i agree with @dgattey seems like the entire code is a mess and should be rewrited, i've tried to fix a few things, and everytime than i fix 1 bug i've found 3 extra bugs.

@christianbundy i've tested your implementation and it doesn't work because:
1.- The playlist only repeated the current track
2.- The shuffle is executed everytime that i've clicked "Next and the Shuffle is Active", at least in itunes or spotify the shuffle (which is not great) has been only applied once.

Modifying playerCtrl.js to the next code will only apply shuffle once (will be needed to remove shuffle from next/Prev button:

`    $scope.shuffle = function($event) {
        var elButton = document.querySelector('.player_shuffle');
        elButton.classList.toggle('active');
        $rootScope.shuffle = !$rootScope.shuffle;
        if( $rootScope.shuffle ){
            utilsService.shuffle();
        }
    };`

**Comment by weblancaster** [comment]
@cinzunzas the reason Soundnode is open source is that people can contribute.. at anytime you want you can send a PR and so far I haven't seen any PR made by you..

Your points are valid and we should address them so please open a issue pointing what you saw and what could be done better if you can't contribute with code.

**Comment by weblancaster** [comment]
As I said before in previous issues.. the shuffle wasn't done to be a complete/fancy algo that would make everybody happy.. was only built to have a start point.

**Comment by cinzunzas** [comment]
@weblancaster happy to contribute and happy to create a community around SoundNode, but in order to make things happen, we need to be focused on the foundations of the app, if i spent several hours reading code is because i want to help.

There's such thing like a forum were we can discuss how to improve the app? it would be great to share ideas and effort between all the people who wants to contribute.

**Comment by christianbundy** [comment]
@weblancaster 
I don't think that @cinzunzas was trying to offend you, so I don't think the defensive comments and justification were necessary. I understand that software is an iterative process, and I appreciate you building the foundation, but the player control code is very unintuitive, and I expect that the majority of the queue code will need to be ripped out if we want a functional shuffle. 

Nobody expects the first draft to be perfect, but maintaining a public project requires that you work with the public rather than criticize them for not contributing PR's. Also, it's worthwhile to mention that @cinzunzas has a version being worked on [here](https://github.com/Soundnode/soundnode-app/compare/master...cinzunzas:master), so I'm not sure your  "and so far I haven't seen any PR made by you.." comment has any merit anyway.

**Comment by weblancaster** [comment]
@christianbundy I didn't take as offensive and I wasn't either criticizing @cinzunzas but just putting all cards on the table.. In open source you always need to make things clear so justification were necessary. 

> Your points are valid and we should address them so please open a issue pointing what you saw and what could be done better if you can't contribute with code even better.

Now, the facts are if you take a look here https://github.com/Soundnode/soundnode-app/pulls you won't see any PR open by @cinzunzas is that a lie? I have seen many people forking Soundnode and started discussions and work on their fork but never a concrete contribution. So I will keep my opinion as looking the concrete facts.

I appreciate @cinzunzas efforts as I did yours. 

Please take a look at the previous issues and PR's for more understanding on how things can work better, many and mostly the times they come with a solution for the problem (as you did with your PR).

Now it's your choice to take this comments as offensive/defensive or that Software is a complicate area and developers have different ideas/perspectives so being clear is part of the work.

**Comment by weblancaster** [comment]
I also agree the code isn't the best to help a developer to get improvements and feats faster and easily that's why I need more people like you guys that see things that can be made better.. so please don't stop pointing out issues but even better if you can open a PR to help out.

**Comment by christianbundy** [comment]
Totally, and I don't think there's any bad blood, I just think that it's usually culturally acceptable to have related discussions on pull requests. Judging by the comments, I think that once @dgattey made a request for comment this turned into a discussion rather than a code review, so it felt strange to see you recommend that we "please open a issue pointing what you saw" rather than to continue the conversation here.

>Now, the facts are if you take a look here https://github.com/Soundnode/soundnode-app/pulls you won't see any PR open by @cinzunzas is that a lie? I have seen many people forking Soundnode and started discussions and work on their fork but never a concrete contribution. So I will keep my opinion as looking the concrete facts.

You're absolutely right, but it isn't a binary option between "never heard of them" and "has contributed a PR" -- I think that "contributing to a discussion" is a valid point on the continuum.

> Now it's your choice to take this comments as offensive/defensive or just not take personally and understand that software is a complicate area and developers have different ideas/perspectives so being clear is part of the work.

None taken. I felt that the micro-managing of the discussion was strange, so I mentioned it. No offense taken, no hostility, etc., honestly. As @cinzunzas asked above: is there somewhere else that we're free to have an open discussion? If that's only allowed in issues (which is fine, albeit strange):
- Create another rule in `CONTRIBUTING.md` prohibiting related discussions in pull requests.
- Create an issue for this discussion where you answer @dgattey's question and reference this PR.
- Close this PR, and ask that others direct the conversation elsewhere.

**Comment by weblancaster** [comment]
closing this PR since no activities (going to start a new PR to improve the shuffling feat)

**Pull request closed without merging**
