### PR TITLE
Restyle the playlist page to allow artwork 

### PR DESCRIPTION
**Pull request by reganlawton**
Quick restyle of the playlist page to support artwork with fallback to first track artwork image for playlists without set artwork. This gives the unfinished look of the playlist page a revamp as i found it very hard to quickly navigate the section.

### CODE REVIEW

**Comment by weblancaster** [comment]
@reganlawton this is great, thanks for contributing.

Now, can you show a screenshot of before and after please?

**Comment by reganlawton** [comment]
@weblancaster  Please find that changes below and in future, I'll do a Before and After with any changes have visual changes.

Before
Before

After
image

**Comment by weblancaster** [comment]
@reganlawton The playlist view/page will change to look like all the other views, the playlists are going to be displayed on the left side navigation under the playlist icon and title and when the user click we navigate to a view that display all songs in the playlist. Does that make sense?

**Comment by reganlawton** [comment]
@weblancaster  From your description you saying the side nav will have a second level, so when the Playlist is selected a second level of the user's playlists shows and when a playlist is selected the page renders out to a match say the Tracks or Likes page.

If this is the case then I can modify the branch to do so. Shouldn't take long and can do when I get a free 30-60mins, if this is correct I can try find some time

**Comment by weblancaster** [comment]
Correct @reganlawton.

Second level below the `Playlist` (which won't be a link anymore) will display a list names of the playlists the user currently has open to streaming. 

When the user clicks on the list on the left side the main view direct to the playlist using the same view as tracks and likes.

**Comment by weblancaster** [comment]
closing this since there hasn't been activity for a while and because I know what to do here.

Thanks for the suggestion @reganlawton

**Pull request closed without merging**
