### PR TITLE
Window action buttons for Windows

### PR DESCRIPTION
**Pull request by Pitros**
Action buttons (close, minimize etc.) will display on right on Windows, as well buttons have correct style.

I did it using directive, but there may be better way.

### CODE REVIEW

**Comment by weblancaster** [comment]
@Pitros this can't be merged.. you will need to rebase with master and push to your `actionButtons` with `--force` to override

**Comment by weblancaster** [comment]
can you also add a screenshot please, so anyone can see how will look like.

**Comment by Pitros** [comment]
Oh god, that was tricky.

@weblancaster: please check can this be merged now.

image

**Comment by Scarwolf** [comment]
Would also appreciate this much morr as soundnode is the only application which has those buttons on the left and thats really confusing.

**Comment by weblancaster** [comment]
I finally got to test on Windows.. thanks for this improvement @Pitros

**Pull request merged**
