### PR TITLE
Cleaning up cache folder

### PR DESCRIPTION
**Pull request by MichielDeMey**
Removed the cache folder
Switched to the newest grunt nodewebkit builder version
Cleaning the dist folder on build

Fixes https://github.com/Soundnode/soundnode-app/issues/224

### CODE REVIEW

**Comment by weblancaster** [comment]
Hey @MichielDeMey everything looks good but what about the download_url?

I have a custom build because of the codecs/libs otherwise if I use the build from the nw.js the audio won't work.

**Comment by MichielDeMey** [comment]
Aha! That explains why the audio wasn't working. :smile:
However, the url gave a 404?

What's the folder structure of the download url on your server?
Maybe enable index browsing for the download path like nwjs does?
See: http://dl.nwjs.io/

**Comment by weblancaster** [comment]
You wont be able to access the folder.

http://www.soundnodeapp.com/build/v0.10.4/node-webkit-v0.10.4-osx-ia32 or node-webkit-v0.10.4-win-ia32

**Comment by MichielDeMey** [comment]
I quickly fixed the download url issue, it seems the grunt-node-webkit-builder is using a different version on npm so I had to update it.

However, the remaining issue is that the zip file somehow is not extracted correctly.

It should be
```
cache/0.10.4
├── cache/0.10.4/osx32
│   ├── cache/0.10.4/osx32/credits.html
│   ├── cache/0.10.4/osx32/node-webkit.app
│   └── cache/0.10.4/osx32/nwsnapshot
└── cache/0.10.4/win32
    ├── cache/0.10.4/win32/credits.html
    ├── cache/0.10.4/win32/ffmpegsumo.dll
    ├── cache/0.10.4/win32/icudtl.dat
    ├── cache/0.10.4/win32/libEGL.dll
    ├── cache/0.10.4/win32/libGLESv2.dll
    ├── cache/0.10.4/win32/locales
    ├── cache/0.10.4/win32/nw.exe
    ├── cache/0.10.4/win32/nw.pak
    └── cache/0.10.4/win32/nwsnapshot.exe
```

But when I use your download URL it's extracted as
```
cache/0.10.4
├── cache/0.10.4/osx32
│   ├── cache/0.10.4/osx32/__MACOSX/
│   └── cache/0.10.4/osx32/node-webkit-v0.10.4-osx-ia32/
└── cache/0.10.4/win32
    ├── cache/0.10.4/win32/__MACOSX/
    └── cache/0.10.4/win32/node-webkit-v0.10.4-win-ia32/
```

Is your zip file somehow different?

**Comment by weblancaster** [comment]
I'm going to check what changed from the old grunt-node-webkit-builder to the new grunt-node-webkit-builder.. because it was supposed to work.

I will get back to you after I'm done testing the build.

**Comment by weblancaster** [comment]
Can you also add  `osx64 ` and `win64 ` @MichielDeMey

**Comment by MichielDeMey** [comment]
As far as I checked, you don't have the 64 bit binaries on your download server?

http://www.soundnodeapp.com/build/v0.10.4/node-webkit-v0.10.4-win-x64.zip
http://www.soundnodeapp.com/build/v0.10.4/node-webkit-v0.10.4-osx-x64.zip

I'll take a look at the zip issue as well.

**Comment by MichielDeMey** [comment]
I've traced the issue back to the fact that your zip has the `__MACOSX` folder and it breaks on this logic since rootFiles.length is `2` in our case.

https://github.com/mllrsohn/node-webkit-builder/blob/master/lib/downloader.js#L164

I added some logic to strip the `__MACOSX` folder and that worked, I'll have to create a PR for this if they are willing to accept it, otherwise you'll have to re-generate your zip files without the `__MACOSX` folder.

**Comment by weblancaster** [comment]
@MichielDeMey I'm going to merge and fix it while I'm upgrading to the latest version of nw.js.

Thanks.

**Pull request merged**
